In [2]:
import numpy as np

a=[[-0.5454,-0.1818,0.1818,0.5454],[-0.1893,0.5681,-0.1893,-0.1893]]




[[-0.5454, -0.1818, 0.1818, 0.5454], [-0.1893, 0.5681, -0.1893, -0.1893]]

In [4]:
import numpy as np

a=[[-0.5454,-0.1818,0.1818,0.5454],[-0.1893,0.5681,-0.1893,-0.1893]]
b=a.transpose()
b

AttributeError: 'list' object has no attribute 'transpose'

In [5]:
import numpy as np

a=np.array([[-0.5454,-0.1818,0.1818,0.5454],[-0.1893,0.5681,-0.1893,-0.1893]])
b=a.transpose()
b

array([[-0.5454, -0.1893],
       [-0.1818,  0.5681],
       [ 0.1818, -0.1893],
       [ 0.5454, -0.1893]])

In [6]:
np.matmul(a,b)

array([[ 0.6610248 , -0.13769532],
       [-0.13769532,  0.43024108]])

In [7]:
import numpy as np

a=np.array([[-1.5,-0.5,0.5,1.5],[-0.25,0.75,-0.25,-0.25]])
b=a.transpose()
x=np.matmul(a,b)

array([[ 5.  , -0.5 ],
       [-0.5 ,  0.75]])

In [8]:
import numpy as np
from numpy import linalg as LA

a=np.array([[-1.5,-0.5,0.5,1.5],[-0.25,0.75,-0.25,-0.25]])
b=a.transpose()
x=np.matmul(a,b)
w, v = LA.eig(x)

In [9]:
import numpy as np
from numpy import linalg as LA

a=np.array([[-1.5,-0.5,0.5,1.5],[-0.25,0.75,-0.25,-0.25]])
b=a.transpose()
x=np.matmul(a,b)
w, v = LA.eig(x)
w;v


array([[ 0.99333206,  0.1152884 ],
       [-0.1152884 ,  0.99333206]])

In [14]:
import numpy as np
from numpy import linalg as LA

a=np.array([[-1.5,-0.5,0.5,1.5],[-0.25,0.75,-0.25,-0.25]])
b=a.transpose()
x=np.matmul(a,b)
w, v = LA.eig(x)
print(v)
print(w)



[[ 0.99333206  0.1152884 ]
 [-0.1152884   0.99333206]]
[5.05803115 0.69196885]


In [15]:
import numpy as np
a=np.array([[-1.5,-0.5,0.5,1.5],[-0.25,0.75,-0.25,-0.25]])
b=a.transpose()

In [16]:
b

array([[-1.5 , -0.25],
       [-0.5 ,  0.75],
       [ 0.5 , -0.25],
       [ 1.5 , -0.25]])

In [17]:
v=([0.993,-0.11])
x=np.matmul(b,v)
x

array([-1.462, -0.579,  0.524,  1.517])

In [18]:
import numpy as np
from numpy import linalg as LA
a=np.array([[0.25,-0.75,0.25,0.25],[-1.5,-0.5,0.5,1.5]])
b=a.transpose()
x=np.matmul(a,b)

w, v = LA.eig(x)
print(v)
print(w)


[[-0.99333206 -0.1152884 ]
 [ 0.1152884  -0.99333206]]
[0.69196885 5.05803115]


In [19]:
import numpy as np
from numpy import linalg as LA
a=np.array([[0.25,-0.75,0.25,0.25],[-1.5,-0.5,0.5,1.5]])
b=a.transpose()
x=np.matmul(a,b)
print(x)
w, v = LA.eig(x)
print(v)
print(w)

[[0.75 0.5 ]
 [0.5  5.  ]]
[[-0.99333206 -0.1152884 ]
 [ 0.1152884  -0.99333206]]
[0.69196885 5.05803115]


In [21]:
v=([0.116,0.9933])
x=np.matmul(b,v)
x

array([-1.46095, -0.58365,  0.52565,  1.51895])